// Mock data for the Training Management System
import { User, Institution, Hall, Training, Nomination, Attendance, Notification } from '../types';

// Demo Users for all roles
export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Dr. Admin Kumar',
    email: 'admin@dmo.gov',
    password: 'admin123', // In real app: hashed
    role: 'master_admin',
    phone: '+91-9876543210',
    designation: 'DMO Administrator',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'user-2',
    name: 'Dr. Priya Sharma',
    email: 'priya@dmo.gov',
    password: 'officer123',
    role: 'program_officer',
    phone: '+91-9876543211',
    designation: 'Senior Program Officer',
    createdAt: new Date('2025-01-02'),
  },
  {
    id: 'user-3',
    name: 'Dr. Rajesh Verma',
    email: 'rajesh@dmo.gov',
    password: 'officer123',
    role: 'program_officer',
    phone: '+91-9876543212',
    designation: 'Program Officer',
    createdAt: new Date('2025-01-03'),
  },
  {
    id: 'user-4',
    name: 'Dr. Anjali Patel',
    email: 'anjali@hospital1.gov',
    password: 'inst123',
    role: 'institutional_admin',
    institutionId: 'inst-1',
    phone: '+91-9876543213',
    designation: 'Medical Superintendent',
    createdAt: new Date('2025-01-04'),
  },
  {
    id: 'user-5',
    name: 'Dr. Suresh Reddy',
    email: 'suresh@hospital2.gov',
    password: 'inst123',
    role: 'institutional_admin',
    institutionId: 'inst-2',
    phone: '+91-9876543214',
    designation: 'Hospital Administrator',
    createdAt: new Date('2025-01-05'),
  },
  {
    id: 'user-6',
    name: 'Nurse Kavita Singh',
    email: 'kavita@hospital1.gov',
    password: 'part123',
    role: 'participant',
    institutionId: 'inst-1',
    phone: '+91-9876543215',
    designation: 'Staff Nurse',
    department: 'General Ward',
    createdAt: new Date('2025-01-10'),
  },
  {
    id: 'user-7',
    name: 'Dr. Amit Desai',
    email: 'amit@hospital1.gov',
    password: 'part123',
    role: 'participant',
    institutionId: 'inst-1',
    phone: '+91-9876543216',
    designation: 'Medical Officer',
    department: 'Emergency',
    createdAt: new Date('2025-01-11'),
  },
  {
    id: 'user-8',
    name: 'Pharmacist Meera Nair',
    email: 'meera@hospital2.gov',
    password: 'part123',
    role: 'participant',
    institutionId: 'inst-2',
    phone: '+91-9876543217',
    designation: 'Pharmacist',
    department: 'Pharmacy',
    createdAt: new Date('2025-01-12'),
  },
  {
    id: 'user-9',
    name: 'Lab Technician Ramesh',
    email: 'ramesh@phc1.gov',
    password: 'part123',
    role: 'participant',
    institutionId: 'inst-3',
    phone: '+91-9876543218',
    designation: 'Lab Technician',
    department: 'Laboratory',
    createdAt: new Date('2025-01-13'),
  },
  {
    id: 'user-10',
    name: 'Dr. Lakshmi Iyer',
    email: 'lakshmi@hospital1.gov',
    password: 'part123',
    role: 'participant',
    institutionId: 'inst-1',
    phone: '+91-9876543219',
    designation: 'Senior Medical Officer',
    department: 'Pediatrics',
    createdAt: new Date('2025-01-14'),
  },
];

export const mockInstitutions: Institution[] = [
  {
    id: 'inst-1',
    name: 'District General Hospital',
    type: 'Hospital',
    location: 'Main City Center',
    contactPerson: 'Dr. Anjali Patel',
    contactEmail: 'anjali@hospital1.gov',
    contactPhone: '+91-9876543213',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'inst-2',
    name: 'Community Health Center - North',
    type: 'CHC',
    location: 'North Zone',
    contactPerson: 'Dr. Suresh Reddy',
    contactEmail: 'suresh@hospital2.gov',
    contactPhone: '+91-9876543214',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'inst-3',
    name: 'Primary Health Center - East',
    type: 'PHC',
    location: 'East Zone',
    contactPerson: 'Dr. Ramakrishnan',
    contactEmail: 'rama@phc1.gov',
    contactPhone: '+91-9876543220',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'inst-4',
    name: 'Primary Health Center - West',
    type: 'PHC',
    location: 'West Zone',
    contactPerson: 'Dr. Geeta Menon',
    contactEmail: 'geeta@phc2.gov',
    contactPhone: '+91-9876543221',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'inst-5',
    name: 'Urban Health Center - South',
    type: 'UHC',
    location: 'South Zone',
    contactPerson: 'Dr. Arun Kumar',
    contactEmail: 'arun@uhc1.gov',
    contactPhone: '+91-9876543222',
    createdAt: new Date('2024-01-01'),
  },
];

export const mockHalls: Hall[] = [
  {
    id: 'hall-1',
    name: 'Main Conference Hall',
    location: 'DMO Building - Ground Floor',
    capacity: 100,
    facilities: ['Projector', 'Air Conditioning', 'Sound System', 'WiFi'],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'hall-2',
    name: 'Training Room A',
    location: 'DMO Building - First Floor',
    capacity: 50,
    facilities: ['Projector', 'Air Conditioning', 'Whiteboard'],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'hall-3',
    name: 'Training Room B',
    location: 'DMO Building - First Floor',
    capacity: 40,
    facilities: ['TV Screen', 'Air Conditioning', 'Whiteboard'],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'hall-4',
    name: 'Auditorium',
    location: 'District Hospital Campus',
    capacity: 200,
    facilities: ['Stage', 'Projector', 'Sound System', 'Air Conditioning', 'WiFi'],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'hall-5',
    name: 'Community Hall',
    location: 'CHC North Campus',
    capacity: 75,
    facilities: ['Projector', 'Fans', 'Tables & Chairs'],
    createdAt: new Date('2024-01-01'),
  },
];

export const mockTrainings: Training[] = [
  {
    id: 'train-1',
    title: 'Emergency Response & First Aid',
    description: 'Comprehensive training on emergency medical response and first aid procedures for healthcare workers.',
    program: 'Emergency Medicine',
    targetAudience: 'Nurses, Paramedics, Medical Officers',
    date: new Date('2026-02-15'),
    startTime: '09:00',
    endTime: '17:00',
    hallId: 'hall-1',
    capacity: 80,
    trainerId: 'user-2',
    createdById: 'user-2',
    requiredInstitutions: ['inst-1', 'inst-2', 'inst-3'],
    status: 'scheduled',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'train-2',
    title: 'Infection Control & Prevention',
    description: 'Training on hospital infection control practices, sterilization, and prevention protocols.',
    program: 'Infection Control',
    targetAudience: 'All Healthcare Staff',
    date: new Date('2026-02-20'),
    startTime: '10:00',
    endTime: '16:00',
    hallId: 'hall-2',
    capacity: 45,
    trainerId: 'user-3',
    createdById: 'user-3',
    requiredInstitutions: ['inst-1', 'inst-2', 'inst-4', 'inst-5'],
    status: 'scheduled',
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'train-3',
    title: 'Maternal & Child Health Care',
    description: 'Best practices in maternal and child healthcare, nutrition, and vaccination programs.',
    program: 'MCH Program',
    targetAudience: 'ANMs, Nurses, Medical Officers',
    date: new Date('2026-02-10'),
    startTime: '09:30',
    endTime: '15:30',
    hallId: 'hall-4',
    capacity: 150,
    trainerId: 'user-2',
    createdById: 'user-2',
    requiredInstitutions: ['inst-1', 'inst-2', 'inst-3', 'inst-4', 'inst-5'],
    status: 'scheduled',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'train-4',
    title: 'Digital Health Records Management',
    description: 'Training on implementing and managing electronic health records systems.',
    program: 'Digital Health',
    targetAudience: 'Administrators, Data Entry Operators',
    date: new Date('2026-01-25'),
    startTime: '10:00',
    endTime: '14:00',
    hallId: 'hall-3',
    capacity: 30,
    trainerId: 'user-3',
    createdById: 'user-3',
    requiredInstitutions: ['inst-1', 'inst-2'],
    status: 'completed',
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'train-5',
    title: 'Tuberculosis Management & DOTS',
    description: 'Comprehensive training on TB diagnosis, treatment, and DOTS implementation.',
    program: 'TB Control Program',
    targetAudience: 'Medical Officers, Lab Technicians',
    date: new Date('2026-03-05'),
    startTime: '09:00',
    endTime: '16:00',
    hallId: 'hall-2',
    capacity: 40,
    trainerId: 'user-2',
    createdById: 'user-2',
    requiredInstitutions: ['inst-3', 'inst-4', 'inst-5'],
    status: 'scheduled',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'train-6',
    title: 'Mental Health First Aid',
    description: 'Training on recognizing mental health issues and providing initial support.',
    program: 'Mental Health',
    targetAudience: 'All Healthcare Workers',
    date: new Date('2026-02-25'),
    startTime: '10:00',
    endTime: '15:00',
    hallId: 'hall-5',
    capacity: 60,
    trainerId: 'user-3',
    createdById: 'user-3',
    requiredInstitutions: ['inst-1', 'inst-2', 'inst-3'],
    status: 'scheduled',
    createdAt: new Date('2026-01-28'),
    updatedAt: new Date('2026-01-28'),
  },
];

export const mockNominations: Nomination[] = [
  // Training 1 nominations
  {
    id: 'nom-1',
    trainingId: 'train-1',
    participantId: 'user-6',
    institutionId: 'inst-1',
    status: 'approved',
    nominatedBy: 'user-4',
    nominatedAt: new Date('2026-01-22'),
    approvedBy: 'user-2',
    approvedAt: new Date('2026-01-23'),
  },
  {
    id: 'nom-2',
    trainingId: 'train-1',
    participantId: 'user-7',
    institutionId: 'inst-1',
    status: 'approved',
    nominatedBy: 'user-4',
    nominatedAt: new Date('2026-01-22'),
    approvedBy: 'user-2',
    approvedAt: new Date('2026-01-23'),
  },
  {
    id: 'nom-3',
    trainingId: 'train-1',
    participantId: 'user-8',
    institutionId: 'inst-2',
    status: 'approved',
    nominatedBy: 'user-5',
    nominatedAt: new Date('2026-01-23'),
    approvedBy: 'user-2',
    approvedAt: new Date('2026-01-24'),
  },
  // Training 2 nominations
  {
    id: 'nom-4',
    trainingId: 'train-2',
    participantId: 'user-6',
    institutionId: 'inst-1',
    status: 'nominated',
    nominatedBy: 'user-4',
    nominatedAt: new Date('2026-01-27'),
  },
  {
    id: 'nom-5',
    trainingId: 'train-2',
    participantId: 'user-10',
    institutionId: 'inst-1',
    status: 'approved',
    nominatedBy: 'user-4',
    nominatedAt: new Date('2026-01-27'),
    approvedBy: 'user-3',
    approvedAt: new Date('2026-01-28'),
  },
  // Training 3 nominations
  {
    id: 'nom-6',
    trainingId: 'train-3',
    participantId: 'user-6',
    institutionId: 'inst-1',
    status: 'approved',
    nominatedBy: 'user-4',
    nominatedAt: new Date('2026-01-18'),
    approvedBy: 'user-2',
    approvedAt: new Date('2026-01-19'),
  },
  {
    id: 'nom-7',
    trainingId: 'train-3',
    participantId: 'user-7',
    institutionId: 'inst-1',
    status: 'approved',
    nominatedBy: 'user-4',
    nominatedAt: new Date('2026-01-18'),
    approvedBy: 'user-2',
    approvedAt: new Date('2026-01-19'),
  },
  {
    id: 'nom-8',
    trainingId: 'train-3',
    participantId: 'user-8',
    institutionId: 'inst-2',
    status: 'rejected',
    nominatedBy: 'user-5',
    nominatedAt: new Date('2026-01-19'),
    approvedBy: 'user-2',
    approvedAt: new Date('2026-01-20'),
    rejectionReason: 'Capacity full',
  },
  // Training 4 (completed) nominations with attendance
  {
    id: 'nom-9',
    trainingId: 'train-4',
    participantId: 'user-7',
    institutionId: 'inst-1',
    status: 'attended',
    nominatedBy: 'user-4',
    nominatedAt: new Date('2026-01-08'),
    approvedBy: 'user-3',
    approvedAt: new Date('2026-01-10'),
  },
  {
    id: 'nom-10',
    trainingId: 'train-4',
    participantId: 'user-8',
    institutionId: 'inst-2',
    status: 'attended',
    nominatedBy: 'user-5',
    nominatedAt: new Date('2026-01-08'),
    approvedBy: 'user-3',
    approvedAt: new Date('2026-01-10'),
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: 'att-1',
    trainingId: 'train-4',
    participantId: 'user-7',
    timestamp: new Date('2026-01-25T10:15:00'),
    method: 'qr',
    qrData: 'QR_train-4_session-1_user-7',
  },
  {
    id: 'att-2',
    trainingId: 'train-4',
    participantId: 'user-8',
    timestamp: new Date('2026-01-25T10:18:00'),
    method: 'qr',
    qrData: 'QR_train-4_session-1_user-8',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    toUserId: 'user-6',
    message: 'You have been nominated for "Emergency Response & First Aid" training on Feb 15, 2026',
    type: 'info',
    read: false,
    createdAt: new Date('2026-01-22'),
    actionUrl: '/trainings/train-1',
  },
  {
    id: 'notif-2',
    toUserId: 'user-6',
    message: 'Your nomination for "Emergency Response & First Aid" has been approved',
    type: 'success',
    read: false,
    createdAt: new Date('2026-01-23'),
    actionUrl: '/trainings/train-1',
  },
  {
    id: 'notif-3',
    toUserId: 'user-2',
    message: 'New nominations pending approval for "Infection Control & Prevention"',
    type: 'warning',
    read: true,
    createdAt: new Date('2026-01-27'),
    actionUrl: '/nominations',
  },
  {
    id: 'notif-4',
    toUserId: 'user-4',
    message: 'Please nominate participants for upcoming trainings',
    type: 'info',
    read: false,
    createdAt: new Date('2026-02-01'),
    actionUrl: '/trainings',
  },
];
